# Generated by Django 4.0.10 on 2024-03-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0029_horaaulacargahoraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cor',
            field=models.CharField(default='branco', max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='periodo',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='webpages.periodo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.IntegerField(choices=[(1, 'Coordenador'), (2, 'Instrutor'), (3, 'Assistente')]),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nif',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nivel',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='vinculo',
            field=models.IntegerField(choices=[(1, 'Horista'), (2, 'Prazo Indeterminado'), (3, 'Temporário'), (4, 'Prazo Determinado')]),
        ),
    ]
