# Generated by Django 4.0.10 on 2024-04-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaTecnologica',
            fields=[
                ('id_area_tecnologica', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_area_tecnologica', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'area_tecnologica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id_aula', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_aula_semana', models.IntegerField(blank=True, null=True)),
                ('tipo_aula', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AulaProfessor',
            fields=[
                ('id_aula_professor', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'aula_professor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AulaSala',
            fields=[
                ('id_aula_sala', models.AutoField(primary_key=True, serialize=False)),
                ('qtd_horas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'aula_sala',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Capacidade',
            fields=[
                ('id_capacidade', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_capacidade', models.CharField(blank=True, max_length=254, null=True)),
                ('tipo_capacidade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'capacidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_evento', models.CharField(blank=True, max_length=100, null=True)),
                ('data_evento', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HoraIntervalo',
            fields=[
                ('id_intervalo', models.AutoField(primary_key=True, serialize=False)),
                ('hora_ini', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hora_intervalo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id_infraestrutura', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_infra', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_infraestrutura', models.IntegerField(blank=True, null=True)),
                ('cor_infraestrutura', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Infraestrutura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id_instituicao', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_instituicao', models.IntegerField(unique=True)),
                ('nome_instiuicao', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'instituicao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id_periodo', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('turno_manha', models.IntegerField(blank=True, null=True)),
                ('turno_tarde', models.IntegerField(blank=True, null=True)),
                ('turno_noite', models.IntegerField(blank=True, null=True)),
                ('dia_seg', models.IntegerField(blank=True, null=True)),
                ('dia_ter', models.IntegerField(blank=True, null=True)),
                ('dia_qua', models.IntegerField(blank=True, null=True)),
                ('dia_qui', models.IntegerField(blank=True, null=True)),
                ('dia_sex', models.IntegerField(blank=True, null=True)),
                ('dia_sab', models.IntegerField(blank=True, null=True)),
                ('dia_dom', models.IntegerField(blank=True, null=True)),
                ('qtd_aula_dia', models.IntegerField(blank=True, null=True)),
                ('qtd_dias_semana_aula', models.IntegerField(blank=True, null=True)),
                ('tempo_aula_min', models.IntegerField(blank=True, null=True)),
                ('hora_intervalo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoDetalhe',
            fields=[
                ('id_periodo_detalhe', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_periodo', models.IntegerField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fim', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'periodo_detalhe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PeriodoIntervalo',
            fields=[
                ('id_periodo_intervalo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'periodo_intervalo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome_pessoa', models.CharField(blank=True, max_length=254, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_pessoa', models.IntegerField(blank=True, null=True)),
                ('vinculo', models.IntegerField(blank=True, null=True)),
                ('cor_pessoa', models.CharField(blank=True, max_length=10, null=True)),
                ('nif', models.FloatField(unique=True)),
                ('situação', models.IntegerField(blank=True, db_column='Situação', null=True)),
            ],
            options={
                'db_table': 'pessoa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PessoaViagem',
            fields=[
                ('id_viagem', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pessoa_viagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_turma', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('cor_turma', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'turma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id_unidade', models.AutoField(primary_key=True, serialize=False)),
                ('descricao_unidade', models.CharField(blank=True, max_length=254, null=True)),
                ('carga_horaria_total', models.IntegerField(blank=True, null=True)),
                ('cor_capacidade', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'unidade',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadeCapacidade',
            fields=[
                ('id_unidade_capacidade', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'unidade_capacidade',
                'managed': False,
            },
        ),
    ]
