# Generated by Django 4.0.10 on 2023-12-27 00:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areatecnologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('inicio', models.DateField()),
                ('termino', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_horas_total', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Infraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(choices=[('laboratorio', 'Laboratório'), ('oficina', 'Oficina'), ('sala_de_aula', 'Sala de Aula')], max_length=20)),
                ('capacidade', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tipocurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tipo_curso', models.CharField(choices=[('cursolivre', 'Curso Livre'), ('cursoregular', 'Curso Regular'), ('cursoFic', 'Curso FIC')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('carga_horaria', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(choices=[('horista', 'Horista'), ('prazo_indeter', 'Prazo Indeterminado'), ('temporario', 'Temporário'), ('prazo_determinado', 'prazo_determinado')], default='prazo_determinado', max_length=20)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='HoratrabProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horatrabIni', models.TimeField()),
                ('horatrabFim', models.TimeField()),
                ('selected_days', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=3), default=list, size=None)),
                ('quanthorames', models.IntegerField()),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpages.pessoa')),
                ('vinculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpages.vinculo')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('calendario_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.calendarioacademico')),
            ],
        ),
        migrations.CreateModel(
            name='DiaLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('e_dia_de_aula', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('calendario_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.calendarioacademico')),
            ],
        ),
        migrations.CreateModel(
            name='CursoUnidadeCurricularProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.curso')),
                ('unidade_curricular', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.unidadecurricular')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='infraestruturas',
            field=models.ManyToManyField(blank=True, to='webpages.infraestrutura'),
        ),
        migrations.AddField(
            model_name='curso',
            name='tipo_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webpages.tipocurso'),
        ),
        migrations.CreateModel(
            name='CalendarioAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.aula')),
                ('dia_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.dialetivo')),
            ],
        ),
        migrations.AddField(
            model_name='aula',
            name='curso_uc_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.cursounidadecurricularprofessor'),
        ),
        migrations.AddField(
            model_name='aula',
            name='infraestrutura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.infraestrutura'),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webpages.pessoa')),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('nivel', models.CharField(blank=True, max_length=100, null=True)),
                ('cursos', models.ManyToManyField(blank=True, to='webpages.curso')),
                ('horario_trabalho', models.ManyToManyField(blank=True, to='webpages.horatrabprof')),
            ],
            bases=('webpages.pessoa',),
        ),
        migrations.AddField(
            model_name='cursounidadecurricularprofessor',
            name='professores',
            field=models.ManyToManyField(to='webpages.professor'),
        ),
    ]
