# Generated by Django 4.0.10 on 2023-12-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='cursos',
        ),
        migrations.AddField(
            model_name='professor',
            name='unidadeCurricular',
            field=models.ManyToManyField(blank=True, to='webpages.unidadecurricular'),
        ),
    ]
