# Generated by Django 4.0.10 on 2023-12-23 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraestrutura',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='infraestrutura',
            name='tipo',
            field=models.CharField(choices=[('laboratorio', 'Laboratório'), ('oficina', 'Oficina'), ('sala_de_aula', 'Sala de Aula')], max_length=20),
        ),
    ]
