# Generated by Django 4.0.10 on 2023-12-27 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_remove_professor_cursos_professor_unidadecurricular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='unidadeCurricular',
        ),
    ]
