# Generated by Django 4.0.10 on 2023-12-27 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_remove_professor_unidadecurricular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursounidadecurricularprofessor',
            name='curso',
        ),
    ]
