# Generated by Django 4.0.10 on 2023-12-28 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_rename_professores_cursounidadecurricularprofessor_professor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursounidadecurricularprofessor',
            name='professor',
        ),
        migrations.AddField(
            model_name='cursounidadecurricularprofessor',
            name='professor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webpages.professor'),
        ),
    ]
