# Generated by Django 4.0.10 on 2023-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0007_calendarioacademico_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data',
            new_name='data_fim',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(default='1970-02-10'),
        ),
    ]
