# Generated by Django 4.0.10 on 2023-12-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0008_rename_data_evento_data_fim_evento_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateField(default='1970-02-15'),
        ),
    ]
