# Generated by Django 4.0.10 on 2024-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0009_alter_evento_data_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areatecnologica',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='horatrabprof',
            options={'ordering': ['pessoa']},
        ),
        migrations.AlterModelOptions(
            name='infraestrutura',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='pessoa',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['pessoa']},
        ),
        migrations.AlterModelOptions(
            name='unidadecurricular',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='professor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
