# Generated by Django 4.0.10 on 2024-02-16 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_alter_areatecnologica_options_alter_curso_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursounidadecurricularprofessor',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.curso'),
        ),
        migrations.AlterField(
            model_name='cursounidadecurricularprofessor',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.professor'),
        ),
    ]
