# Generated by Django 4.0.10 on 2024-02-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0012_remove_aula_horario_fim_remove_aula_horario_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='infraestruturas',
        ),
        migrations.CreateModel(
            name='AulaInfraestrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveIntegerField()),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aula_infraestruturas', to='webpages.aula')),
                ('infraestrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.infraestrutura')),
            ],
        ),
    ]
