# Generated by Django 4.0.10 on 2024-02-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0015_alter_pessoa_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='vinculo',
            field=models.CharField(choices=[('horista', 'Horista'), ('prazo indeterminado', 'Prazo Indeterminado'), ('temporario', 'Temporário'), ('prazo determinado', 'prazo Determinado')], default='prazo determinado', max_length=20),
        ),
    ]
