# Generated by Django 4.0.10 on 2024-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0016_alter_pessoa_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='vinculo',
            field=models.CharField(choices=[('Horista', 'Horista'), ('Prazo Indeterminado', 'Prazo Indeterminado'), ('Temporário', 'Temporário'), ('Prazo Determinado', 'Prazo Determinado')], default='Prazo Determinado', max_length=20),
        ),
    ]
