# Generated by Django 4.0.10 on 2024-02-23 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0018_pessoa_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='vinculo',
            field=models.CharField(choices=[('Horista', 'Horista'), ('Prazo Indeterminado', 'Prazo Indeterminado'), ('Temporario', 'Temporario'), ('Prazo Determinado', 'Prazo Determinado')], default='Prazo Determinado', max_length=20),
        ),
    ]
