# Generated by Django 4.0.10 on 2024-02-29 16:09

import django.contrib.postgres.fields
from django.db import migrations, models
import webpages.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0020_alter_pessoa_vinculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='calendario_academico',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='nome',
        ),
        migrations.AddField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(default='2024-02-29', validators=[webpages.models.validar_data]),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='horatrabprof',
            name='selected_days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=3), default=list, size=None),
        ),
    ]
