# Generated by Django 4.0.10 on 2024-02-29 17:08

from django.db import migrations, models
import webpages.models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0021_remove_evento_calendario_academico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateField(default='1920/02/02', validators=[webpages.models.validar_data]),
        ),
    ]
