# Generated by Django 4.0.10 on 2024-02-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0022_cadastroescola_alter_evento_data_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacidadesFundamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Fundamentos'), (2, 'Técnica'), (3, 'Socioemocional')])),
            ],
        ),
    ]
