# Generated by Django 4.0.10 on 2024-02-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0023_capacidadesfundamentos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unidadecurricular',
            options={'ordering': ['descricao']},
        ),
        migrations.RenameField(
            model_name='unidadecurricular',
            old_name='nome',
            new_name='descricao',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='horas_laboratorio',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='horas_oficina',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='horas_sala_aula',
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='capacidadeFundamentos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpages.capacidadesfundamentos'),
        ),
        migrations.AddField(
            model_name='unidadecurricular',
            name='cor',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
