# Generated by Django 4.0.10 on 2024-02-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0024_alter_unidadecurricular_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeCapacidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.unidadecurricular')),
            ],
        ),
    ]
