# Generated by Django 4.0.10 on 2024-03-01 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0025_unidadecapacidade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='horatrabprof',
            options={},
        ),
        migrations.RemoveField(
            model_name='horatrabprof',
            name='pessoa',
        ),
        migrations.AddField(
            model_name='unidadecapacidade',
            name='capacidade',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webpages.capacidadesfundamentos'),
        ),
    ]
