# Generated by Django 4.0.10 on 2024-03-01 16:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0026_alter_horatrabprof_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('periodo', models.CharField(choices=[('Manhã', 'manhã'), ('Tarde', 'tarde'), ('Noite', 'noite')], max_length=5)),
                ('diasSemana', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Seg', 'Segunda'), ('Ter', 'Terça'), ('Qua', 'Quarta'), ('Qui', 'Quinta'), ('Sex', 'Sexta'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=3), default=list, size=None)),
                ('aulasPorDia', models.IntegerField()),
                ('diasAula', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='HoratrabProf',
        ),
    ]
