# Generated by Django 4.0.10 on 2024-03-01 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0028_alter_periodo_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoraAulaCargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('tipoRegistro', models.IntegerField(choices=[(1, 'Aula'), (2, 'Intervalo'), (3, 'Viagem'), (4, 'Carga Horaria')])),
                ('horaInicio', models.TimeField()),
                ('horaFim', models.TimeField()),
                ('dataInicio', models.DateField()),
                ('dataFim', models.DateField()),
                ('periodo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webpages.periodo')),
            ],
        ),
    ]
