# Generated by Django 4.0.10 on 2024-03-01 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0030_pessoa_cor_pessoa_periodo_alter_pessoa_cargo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webpages.periodo'),
        ),
    ]
