# Generated by Django 4.0.10 on 2024-03-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0031_alter_pessoa_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraestrutura',
            name='cor',
            field=models.CharField(default='cinza', max_length=50),
        ),
        migrations.AlterField(
            model_name='infraestrutura',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Laboratório'), (2, 'Oficina'), (3, 'Sala de Aula')]),
        ),
    ]
