# Generated by Django 4.0.10 on 2024-03-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0029_horaaulacargahoraria'),
    ]

    operations = [
        migrations.AddField(
            model_name='horaaulacargahoraria',
            name='periodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webpages.periodo'),
        ),
    ]
