# Generated by Django 4.0.10 on 2024-02-22 17:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0013_remove_aula_infraestruturas_aulainfraestrutura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidadesSociais', models.TextField(blank=True)),
                ('capacidadeTecnicaFundamentos', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='vinculo',
            name='pessoa',
        ),
        migrations.RenameField(
            model_name='horatrabprof',
            old_name='horatrabFim',
            new_name='horaEnter1',
        ),
        migrations.RenameField(
            model_name='horatrabprof',
            old_name='horatrabIni',
            new_name='horaSaida1',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tipo_curso',
        ),
        migrations.RemoveField(
            model_name='cursounidadecurricularprofessor',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='capacidadeTecnicaFundamentos',
        ),
        migrations.RemoveField(
            model_name='unidadecurricular',
            name='capacidadesSociais',
        ),
        migrations.AddField(
            model_name='curso',
            name='curso_livre',
            field=models.CharField(choices=[('Iniciação', 'Iniciação'), ('Qualificação', 'Qualificação'), ('Aperfeiçoamento', 'Aperfeiçoamento'), ('Especialização', 'Especialização')], default='Especialização', max_length=30),
        ),
        migrations.AddField(
            model_name='curso',
            name='curso_regular',
            field=models.CharField(choices=[('Aprendizagem industrial', 'Aprendizagem industrial'), ('Técnico', 'Técnico')], default='Aprendizagem industrial', max_length=30),
        ),
        migrations.AddField(
            model_name='cursounidadecurricularprofessor',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webpages.pessoa'),
        ),
        migrations.AddField(
            model_name='horatrabprof',
            name='data_fim',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='horatrabprof',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='horatrabprof',
            name='horaEnter2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horatrabprof',
            name='horaSaida2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(choices=[('Coordenador', 'Coordenador'), ('Instrutor', 'Instrutor'), ('Assistente', 'Assistente')], default='Assistente', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nif',
            field=models.CharField(default='00000', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nivel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='vinculo',
            field=models.CharField(choices=[('horista', 'Horista'), ('prazo_indeter', 'Prazo Indeterminado'), ('temporario', 'Temporário'), ('prazo_determinado', 'prazo_determinado')], default='prazo_determinado', max_length=20),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='Tipocurso',
        ),
        migrations.DeleteModel(
            name='Vinculo',
        ),
        migrations.AddField(
            model_name='capacidades',
            name='unidadeCurricular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webpages.unidadecurricular'),
        ),
    ]
