# Generated by Django 4.0.10 on 2024-03-01 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0032_remove_horaaulacargahoraria_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaaulacargahoraria',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, serialize=False, to='webpages.periodo'),
        ),
    ]
